apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
    - name: redis-port
      port: 6379
      targetPort: 6379
    - name: alpine-port
      port: 8082  # Can be any port, since the Alpine container is sleeping
      targetPort: 8080
  type: ClusterIP

