apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container-one
        image: nginx:latest   # Updated image
        ports:
        - containerPort: 80
      - name: container-two
        image: redis:6.2.1    # Updated image
        ports:
        - containerPort: 6379
      - name: container-three
        image: alpine:3.13    # Updated image
        command: ["sleep", "3600"]

